# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "fluent-plugin-record-modifier", "~> 2.0"

gem "fluent-plugin-concat", "~> 2.4"

gem "fluent-plugin-detect-exceptions", "~> 0.0.12"

gem "fluent-plugin-kubernetes_metadata_filter", "~> 2.2"

gem "fluent-plugin-multi-format-parser", "~> 1.0"

gem "fluent-plugin-prometheus", "~> 1.4"

gem "oj", "~> 3.8"

gem "fluent-plugin-systemd", "~> 1.0"

gem "fluent-plugin-cloudwatch-logs", "~> 0.10.2"

gem "fluent-plugin-s3", "~> 1.1"

gem "fluent-plugin-sumologic_output", "~> 1.5"

gem "fluent-plugin-google-cloud", "~> 0.10.0"

gem "fluent-plugin-filter_where", "~> 1.0"
